apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: my-app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: my-app
      env: dev
  template:
    metadata:
      name: my-pod
      labels:
        app: my-app
        env: dev
    spec:
      containers:
      - name: node
        image: samyakkasture/app
        ports:
        - containerPort: 3000

---
kind: Service
apiVersion: v1
metadata:
  name:  my-svc
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  
spec:
  selector:
    app:  my-app
  type:   LoadBalancer
  ports:
  - name:  node
    port:  3000
    targetPort:  3000
...
